import type {
    InvoiceLineResponse,
    InvoiceReceiptResponse,
    InvoiceResponse,
} from "@/lib/api/finance/invoices";

const ORG_ID = "org_hd_millwork";

export const invoiceCustomers = [
    { id: "cust_01", name: "Cedar & Co." },
    { id: "cust_02", name: "Northwind Cabinetry" },
    { id: "cust_03", name: "Marston Architecture" },
    { id: "cust_04", name: "Brookfield Interiors" },
    { id: "cust_05", name: "Bramble Home Goods" },
    { id: "cust_06", name: "Halverson Studio" },
    { id: "cust_07", name: "Riverstone Hotels" },
    { id: "cust_08", name: "Aldgate Properties" },
] as const;

export const revenueAccounts = [
    { id: "acc_4000", code: "4000", name: "Sales — Cabinetry" },
    { id: "acc_4010", code: "4010", name: "Sales — Custom millwork" },
    { id: "acc_4020", code: "4020", name: "Sales — Installation" },
    { id: "acc_4100", code: "4100", name: "Sales — Replacement parts" },
] as const;

const today = new Date("2026-05-10");
const daysFromToday = (offset: number) => {
    const d = new Date(today);
    d.setDate(d.getDate() + offset);
    return d.toISOString().slice(0, 10);
};
const isoDateTime = (offset: number) => {
    const d = new Date(today);
    d.setDate(d.getDate() + offset);
    d.setHours(14, 32, 0, 0);
    return d.toISOString();
};

const line = (accountId: string, description: string, amount: string): InvoiceLineResponse => {
    const acc = revenueAccounts.find((a) => a.id === accountId)!;
    return {
        accountId,
        accountCode: acc.code,
        accountName: acc.name,
        amount,
        description,
    };
};

const receipt = (
    id: string,
    invoiceId: string,
    offset: number,
    amount: string,
    paymentMethod: InvoiceReceiptResponse["paymentMethod"],
    referenceNumber: string,
): InvoiceReceiptResponse => ({
    id,
    invoiceId,
    receiptDate: daysFromToday(offset),
    amount,
    baseCurrencyAmount: amount,
    exchangeRate: "1.0",
    paymentMethod,
    referenceNumber,
    journalEntryId: `je_${id}`,
    createdBy: "Emma Voss",
    createdAt: isoDateTime(offset),
});

type InvoiceSeed = Omit<
    InvoiceResponse,
    | "organizationId"
    | "exchangeRate"
    | "baseCurrencyAmount"
    | "baseCurrencyTaxAmount"
    | "baseCurrencyAmountReceived"
    | "createdAt"
    | "updatedAt"
> & { _createdOffset: number };

const seeds: InvoiceSeed[] = [
    {
        id: "inv_01",
        invoiceNumber: "INV-2046",
        customerId: "cust_01",
        customerName: "Cedar & Co.",
        date: daysFromToday(-22),
        dueDate: daysFromToday(-18),
        referenceNumber: "PO-CEDAR-118",
        taxGroupId: null,
        status: "PARTIALLY_PAID",
        lines: [
            line("acc_4000", "Maple shaker doors, set of 14", "5800.00"),
            line("acc_4020", "On-site installation, 2 days", "2620.00"),
        ],
        totalAmount: "8420.00",
        taxAmount: "0.00",
        amountReceived: "3000.00",
        currencyCode: "USD",
        journalEntryId: "je_inv_01",
        createdBy: "Emma Voss",
        approvedAt: isoDateTime(-21),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -22,
    },
    {
        id: "inv_02",
        invoiceNumber: "INV-2049",
        customerId: "cust_02",
        customerName: "Northwind Cabinetry",
        date: daysFromToday(-14),
        dueDate: daysFromToday(-10),
        referenceNumber: null,
        taxGroupId: null,
        status: "APPROVED",
        lines: [line("acc_4010", "Walnut bookmatched panels (Q2 order)", "12480.50")],
        totalAmount: "12480.50",
        taxAmount: "0.00",
        amountReceived: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_inv_02",
        createdBy: "Emma Voss",
        approvedAt: isoDateTime(-13),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -14,
    },
    {
        id: "inv_03",
        invoiceNumber: "INV-2051",
        customerId: "cust_03",
        customerName: "Marston Architecture",
        date: daysFromToday(-10),
        dueDate: daysFromToday(-6),
        referenceNumber: null,
        taxGroupId: null,
        status: "APPROVED",
        lines: [line("acc_4010", "Reception desk, walnut + brass", "2510.00")],
        totalAmount: "2510.00",
        taxAmount: "0.00",
        amountReceived: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_inv_03",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-9),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -10,
    },
    {
        id: "inv_04",
        invoiceNumber: "INV-2054",
        customerId: "cust_04",
        customerName: "Brookfield Interiors",
        date: daysFromToday(-3),
        dueDate: daysFromToday(2),
        referenceNumber: null,
        taxGroupId: null,
        status: "DRAFT",
        lines: [
            line("acc_4000", "Built-in shelving, 8 linear feet", "4280.00"),
            line("acc_4100", "Drawer slides + hardware", "1700.00"),
        ],
        totalAmount: "5980.00",
        taxAmount: "0.00",
        amountReceived: "0.00",
        currencyCode: "USD",
        journalEntryId: null,
        createdBy: "Emma Voss",
        approvedAt: null,
        approvedBy: null,
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -3,
    },
    {
        id: "inv_05",
        invoiceNumber: "INV-2055",
        customerId: "cust_05",
        customerName: "Bramble Home Goods",
        date: daysFromToday(-2),
        dueDate: daysFromToday(5),
        referenceNumber: null,
        taxGroupId: null,
        status: "DRAFT",
        lines: [line("acc_4100", "Replacement door fronts (4)", "1840.00")],
        totalAmount: "1840.00",
        taxAmount: "0.00",
        amountReceived: "0.00",
        currencyCode: "USD",
        journalEntryId: null,
        createdBy: "Emma Voss",
        approvedAt: null,
        approvedBy: null,
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -2,
    },
    {
        id: "inv_06",
        invoiceNumber: "INV-2042",
        customerId: "cust_01",
        customerName: "Cedar & Co.",
        date: daysFromToday(-40),
        dueDate: daysFromToday(-25),
        referenceNumber: "PO-CEDAR-094",
        taxGroupId: null,
        status: "PAID",
        lines: [line("acc_4000", "Cabinet refacing — Phase 1", "5420.00")],
        totalAmount: "5420.00",
        taxAmount: "0.00",
        amountReceived: "5420.00",
        currencyCode: "USD",
        journalEntryId: "je_inv_06",
        createdBy: "Emma Voss",
        approvedAt: isoDateTime(-39),
        approvedBy: "Emma Voss",
        paidAt: isoDateTime(-22),
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -40,
    },
    {
        id: "inv_07",
        invoiceNumber: "INV-2038",
        customerId: "cust_06",
        customerName: "Halverson Studio",
        date: daysFromToday(-65),
        dueDate: daysFromToday(-50),
        referenceNumber: "HS-BUILD-22",
        taxGroupId: null,
        status: "PAID",
        lines: [line("acc_4010", "Studio millwork, full fitout", "18420.00")],
        totalAmount: "18420.00",
        taxAmount: "0.00",
        amountReceived: "18420.00",
        currencyCode: "USD",
        journalEntryId: "je_inv_07",
        createdBy: "Emma Voss",
        approvedAt: isoDateTime(-64),
        approvedBy: "Emma Voss",
        paidAt: isoDateTime(-44),
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -65,
    },
    {
        id: "inv_08",
        invoiceNumber: "INV-2050",
        customerId: "cust_07",
        customerName: "Riverstone Hotels",
        date: daysFromToday(-12),
        dueDate: daysFromToday(18),
        referenceNumber: "RS-LOBBY-A",
        taxGroupId: null,
        status: "APPROVED",
        lines: [
            line("acc_4010", "Lobby reception, custom oak", "9840.00"),
            line("acc_4020", "Installation crew, 4 days", "3200.00"),
        ],
        totalAmount: "13040.00",
        taxAmount: "0.00",
        amountReceived: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_inv_08",
        createdBy: "Emma Voss",
        approvedAt: isoDateTime(-11),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -12,
    },
    {
        id: "inv_09",
        invoiceNumber: "INV-2053",
        customerId: "cust_08",
        customerName: "Aldgate Properties",
        date: daysFromToday(-5),
        dueDate: daysFromToday(25),
        referenceNumber: null,
        taxGroupId: null,
        status: "APPROVED",
        lines: [line("acc_4000", "Pantry cabinetry, two-tone", "6720.00")],
        totalAmount: "6720.00",
        taxAmount: "0.00",
        amountReceived: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_inv_09",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-4),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -5,
    },
    {
        id: "inv_10",
        invoiceNumber: "INV-2048",
        customerId: "cust_03",
        customerName: "Marston Architecture",
        date: daysFromToday(-18),
        dueDate: daysFromToday(-3),
        referenceNumber: null,
        taxGroupId: null,
        status: "PARTIALLY_PAID",
        lines: [line("acc_4010", "Conference room paneling", "7400.00")],
        totalAmount: "7400.00",
        taxAmount: "0.00",
        amountReceived: "4000.00",
        currencyCode: "USD",
        journalEntryId: "je_inv_10",
        createdBy: "Emma Voss",
        approvedAt: isoDateTime(-17),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -18,
    },
    {
        id: "inv_11",
        invoiceNumber: "INV-2052",
        customerId: "cust_04",
        customerName: "Brookfield Interiors",
        date: daysFromToday(-7),
        dueDate: daysFromToday(8),
        referenceNumber: null,
        taxGroupId: null,
        status: "DRAFT",
        lines: [line("acc_4000", "Custom built-ins, second floor", "9120.00")],
        totalAmount: "9120.00",
        taxAmount: "0.00",
        amountReceived: "0.00",
        currencyCode: "USD",
        journalEntryId: null,
        createdBy: "Emma Voss",
        approvedAt: null,
        approvedBy: null,
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -7,
    },
    {
        id: "inv_12",
        invoiceNumber: "INV-2032",
        customerId: "cust_02",
        customerName: "Northwind Cabinetry",
        date: daysFromToday(-95),
        dueDate: daysFromToday(-80),
        referenceNumber: null,
        taxGroupId: null,
        status: "VOID",
        lines: [line("acc_4000", "Original Q1 order — replaced by INV-2034", "4200.00")],
        totalAmount: "4200.00",
        taxAmount: "0.00",
        amountReceived: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_inv_12",
        createdBy: "Emma Voss",
        approvedAt: isoDateTime(-94),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: isoDateTime(-90),
        voidedBy: "Emma Voss",
        voidReason: "Customer requested re-quote with adjusted scope.",
        _createdOffset: -95,
    },
    {
        id: "inv_13",
        invoiceNumber: "INV-2056",
        customerId: "cust_05",
        customerName: "Bramble Home Goods",
        date: daysFromToday(-1),
        dueDate: daysFromToday(14),
        referenceNumber: null,
        taxGroupId: null,
        status: "DRAFT",
        lines: [
            line("acc_4100", "Hardware refresh — knobs and pulls", "612.00"),
            line("acc_4020", "Site visit + measurement", "228.00"),
        ],
        totalAmount: "840.00",
        taxAmount: "0.00",
        amountReceived: "0.00",
        currencyCode: "USD",
        journalEntryId: null,
        createdBy: "Hadi Karimov",
        approvedAt: null,
        approvedBy: null,
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -1,
    },
    {
        id: "inv_14",
        invoiceNumber: "INV-2047",
        customerId: "cust_07",
        customerName: "Riverstone Hotels",
        date: daysFromToday(-30),
        dueDate: daysFromToday(-15),
        referenceNumber: "RS-SUITES",
        taxGroupId: null,
        status: "PARTIALLY_PAID",
        lines: [line("acc_4010", "Suite headboards, set of 22", "11200.00")],
        totalAmount: "11200.00",
        taxAmount: "0.00",
        amountReceived: "5600.00",
        currencyCode: "USD",
        journalEntryId: "je_inv_14",
        createdBy: "Emma Voss",
        approvedAt: isoDateTime(-29),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -30,
    },
    {
        id: "inv_15",
        invoiceNumber: "INV-2057",
        customerId: "cust_08",
        customerName: "Aldgate Properties",
        date: daysFromToday(0),
        dueDate: daysFromToday(30),
        referenceNumber: null,
        taxGroupId: null,
        status: "DRAFT",
        lines: [line("acc_4010", "Lobby millwork, lobby B", "14800.00")],
        totalAmount: "14800.00",
        taxAmount: "0.00",
        amountReceived: "0.00",
        currencyCode: "USD",
        journalEntryId: null,
        createdBy: "Emma Voss",
        approvedAt: null,
        approvedBy: null,
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: 0,
    },
];

export const invoices: InvoiceResponse[] = seeds.map(({ _createdOffset, ...seed }) => ({
    ...seed,
    organizationId: ORG_ID,
    exchangeRate: "1.0",
    baseCurrencyAmount: seed.totalAmount,
    baseCurrencyTaxAmount: seed.taxAmount,
    baseCurrencyAmountReceived: seed.amountReceived,
    createdAt: isoDateTime(_createdOffset),
    updatedAt: isoDateTime(_createdOffset),
}));

export const invoiceReceipts: InvoiceReceiptResponse[] = [
    receipt("rcpt_01", "inv_01", -12, "3000.00", "BANK_TRANSFER", "ACH-44218"),
    receipt("rcpt_02", "inv_06", -22, "5420.00", "CHECK", "Check #4422"),
    receipt("rcpt_03", "inv_07", -44, "18420.00", "BANK_TRANSFER", "ACH-43881"),
    receipt("rcpt_04", "inv_10", -7, "4000.00", "BANK_TRANSFER", "ACH-44312"),
    receipt("rcpt_05", "inv_14", -14, "5600.00", "BANK_TRANSFER", "ACH-44102"),
];
