import type { AccountResponse } from "@/lib/api/finance/accounts";
import { MOCK_TODAY } from "../../_data/mock-anchor";

const ORG_ID = "org_hd_millwork";

const isoDateTime = (offset: number) => {
    const d = new Date(MOCK_TODAY);
    d.setDate(d.getDate() + offset);
    d.setHours(8, 0, 0, 0);
    return d.toISOString();
};

type Seed = Omit<AccountResponse, "organizationId" | "createdAt" | "updatedAt"> & { _createdOffset: number };

const seeds: Seed[] = [
    // Assets
    {
        id: "acc_1000",
        code: "1000",
        name: "Cash",
        description: "Operating checking account",
        type: "ASSET",
        parentId: null,
        isActive: true,
        isSystemAccount: true,
        _createdOffset: -1500,
    },
    {
        id: "acc_1100",
        code: "1100",
        name: "Accounts receivable",
        description: "Customer balances owed to us",
        type: "ASSET",
        parentId: null,
        isActive: true,
        isSystemAccount: true,
        _createdOffset: -1500,
    },
    {
        id: "acc_1200",
        code: "1200",
        name: "Inventory — Raw materials",
        description: "Lumber, hardware, finishes on hand",
        type: "ASSET",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1450,
    },
    {
        id: "acc_1210",
        code: "1210",
        name: "Inventory — Work in progress",
        description: null,
        type: "ASSET",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1450,
    },
    {
        id: "acc_1700",
        code: "1700",
        name: "Shop equipment",
        description: null,
        type: "ASSET",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1400,
    },
    {
        id: "acc_1750",
        code: "1750",
        name: "Accumulated depreciation",
        description: "Contra-asset, equipment",
        type: "ASSET",
        parentId: "acc_1700",
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1400,
    },

    // Liabilities
    {
        id: "acc_2100",
        code: "2100",
        name: "Accounts payable",
        description: "Vendor balances we owe",
        type: "LIABILITY",
        parentId: null,
        isActive: true,
        isSystemAccount: true,
        _createdOffset: -1500,
    },
    {
        id: "acc_2150",
        code: "2150",
        name: "Accrued liabilities",
        description: "Wages, taxes, and similar accruals",
        type: "LIABILITY",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1450,
    },
    {
        id: "acc_2200",
        code: "2200",
        name: "Sales tax payable",
        description: null,
        type: "LIABILITY",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1400,
    },

    // Equity
    {
        id: "acc_3000",
        code: "3000",
        name: "Owner's capital",
        description: null,
        type: "EQUITY",
        parentId: null,
        isActive: true,
        isSystemAccount: true,
        _createdOffset: -1500,
    },
    {
        id: "acc_3100",
        code: "3100",
        name: "Retained earnings",
        description: null,
        type: "EQUITY",
        parentId: null,
        isActive: true,
        isSystemAccount: true,
        _createdOffset: -1500,
    },

    // Revenue
    {
        id: "acc_4000",
        code: "4000",
        name: "Sales — Cabinetry",
        description: null,
        type: "REVENUE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1400,
    },
    {
        id: "acc_4010",
        code: "4010",
        name: "Sales — Custom millwork",
        description: null,
        type: "REVENUE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1400,
    },
    {
        id: "acc_4020",
        code: "4020",
        name: "Sales — Installation",
        description: null,
        type: "REVENUE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1400,
    },
    {
        id: "acc_4100",
        code: "4100",
        name: "Sales — Replacement parts",
        description: null,
        type: "REVENUE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -800,
    },
    {
        id: "acc_4900",
        code: "4900",
        name: "Discounts and allowances",
        description: "Contra-revenue",
        type: "REVENUE",
        parentId: null,
        isActive: false,
        isSystemAccount: false,
        _createdOffset: -1200,
    },

    // Expense
    {
        id: "acc_5000",
        code: "5000",
        name: "COGS — Lumber",
        description: null,
        type: "EXPENSE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1400,
    },
    {
        id: "acc_5010",
        code: "5010",
        name: "COGS — Hardware & finishes",
        description: null,
        type: "EXPENSE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1400,
    },
    {
        id: "acc_5020",
        code: "5020",
        name: "COGS — Subcontractors",
        description: null,
        type: "EXPENSE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1400,
    },
    {
        id: "acc_6100",
        code: "6100",
        name: "Utilities",
        description: null,
        type: "EXPENSE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1400,
    },
    {
        id: "acc_6200",
        code: "6200",
        name: "Insurance",
        description: null,
        type: "EXPENSE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1300,
    },
    {
        id: "acc_6300",
        code: "6300",
        name: "Freight & shipping",
        description: null,
        type: "EXPENSE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1300,
    },
    {
        id: "acc_6400",
        code: "6400",
        name: "Salaries & wages",
        description: null,
        type: "EXPENSE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1500,
    },
    {
        id: "acc_6500",
        code: "6500",
        name: "Depreciation",
        description: null,
        type: "EXPENSE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -1300,
    },
    {
        id: "acc_6600",
        code: "6600",
        name: "Office supplies",
        description: null,
        type: "EXPENSE",
        parentId: null,
        isActive: true,
        isSystemAccount: false,
        _createdOffset: -900,
    },
];

export const accounts: AccountResponse[] = seeds.map(({ _createdOffset, ...rest }) => ({
    ...rest,
    organizationId: ORG_ID,
    createdAt: isoDateTime(_createdOffset),
    updatedAt: isoDateTime(_createdOffset + 30),
}));
