import type { BillRow, InvoiceRow, JournalRow, Kpi, TrendPoint } from "./types";

export const orgGreeting = {
    name: "Emma",
    organization: "Hollis & Dray Millwork",
    fiscalYearLabel: "FY 2026 · Q2",
} as const;

export const kpis: Kpi[] = [
    {
        label: "Cash on hand",
        value: "284620.41",
        currencyCode: "USD",
        delta: 0.062,
        detail: "Across 3 accounts",
        tone: "neutral",
    },
    {
        label: "Accounts receivable",
        value: "112480.00",
        currencyCode: "USD",
        delta: -0.034,
        detail: "18 open invoices",
        tone: "neutral",
    },
    {
        label: "Accounts payable",
        value: "47215.88",
        currencyCode: "USD",
        delta: 0.118,
        detail: "9 unpaid bills",
        tone: "neutral",
    },
    {
        label: "Overdue",
        value: "23410.00",
        currencyCode: "USD",
        delta: 0.21,
        detail: "5 invoices · 2 bills",
        tone: "accent",
    },
    {
        label: "Net income MTD",
        value: "38940.12",
        currencyCode: "USD",
        delta: 0.082,
        detail: "vs. prior month",
        tone: "positive",
    },
    {
        label: "Unposted entries",
        value: "7",
        currencyCode: "",
        delta: null,
        detail: "Journal needs review",
        tone: "warning",
    },
];

export const invoiceQueue: InvoiceRow[] = [
    {
        id: "inv_01",
        invoiceNumber: "INV-2046",
        customerName: "Cedar & Co.",
        dueDate: "2026-04-22",
        daysOverdue: -18,
        status: "PARTIALLY_PAID",
        totalAmount: "8420.00",
        amountReceived: "3000.00",
        currencyCode: "USD",
    },
    {
        id: "inv_02",
        invoiceNumber: "INV-2049",
        customerName: "Northwind Cabinetry",
        dueDate: "2026-04-30",
        daysOverdue: -10,
        status: "APPROVED",
        totalAmount: "12480.50",
        amountReceived: "0.00",
        currencyCode: "USD",
    },
    {
        id: "inv_03",
        invoiceNumber: "INV-2051",
        customerName: "Marston Architecture",
        dueDate: "2026-05-04",
        daysOverdue: -6,
        status: "APPROVED",
        totalAmount: "2510.00",
        amountReceived: "0.00",
        currencyCode: "USD",
    },
    {
        id: "inv_04",
        invoiceNumber: "INV-2054",
        customerName: "Brookfield Interiors",
        dueDate: "2026-05-12",
        daysOverdue: 2,
        status: "DRAFT",
        totalAmount: "5980.00",
        amountReceived: "0.00",
        currencyCode: "USD",
    },
    {
        id: "inv_05",
        invoiceNumber: "INV-2055",
        customerName: "Bramble Home Goods",
        dueDate: "2026-05-15",
        daysOverdue: 5,
        status: "DRAFT",
        totalAmount: "1840.00",
        amountReceived: "0.00",
        currencyCode: "USD",
    },
];

export const billQueue: BillRow[] = [
    {
        id: "bill_01",
        billNumber: "BILL-0312",
        vendorName: "Pacific Hardwoods Ltd.",
        dueDate: "2026-04-28",
        daysOverdue: -12,
        status: "APPROVED",
        totalAmount: "9210.00",
        amountPaid: "0.00",
        currencyCode: "USD",
    },
    {
        id: "bill_02",
        billNumber: "BILL-0315",
        vendorName: "Forge Tooling Supply",
        dueDate: "2026-05-02",
        daysOverdue: -8,
        status: "APPROVED",
        totalAmount: "1340.50",
        amountPaid: "0.00",
        currencyCode: "USD",
    },
    {
        id: "bill_03",
        billNumber: "BILL-0318",
        vendorName: "Greenline Logistics",
        dueDate: "2026-05-08",
        daysOverdue: -2,
        status: "DRAFT",
        totalAmount: "488.00",
        amountPaid: "0.00",
        currencyCode: "USD",
    },
    {
        id: "bill_04",
        billNumber: "BILL-0319",
        vendorName: "Hudson Power & Light",
        dueDate: "2026-05-14",
        daysOverdue: 4,
        status: "DRAFT",
        totalAmount: "722.40",
        amountPaid: "0.00",
        currencyCode: "USD",
    },
    {
        id: "bill_05",
        billNumber: "BILL-0321",
        vendorName: "Atlas Insurance Group",
        dueDate: "2026-05-20",
        daysOverdue: 10,
        status: "DRAFT",
        totalAmount: "1850.00",
        amountPaid: "0.00",
        currencyCode: "USD",
    },
];

export const recentJournal: JournalRow[] = [
    {
        id: "je_01",
        entryNumber: "JE-1042",
        date: "2026-05-09",
        description: "Payroll accrual · May 1–9",
        status: "POSTED",
        source: "SYSTEM",
        amount: "21480.00",
        currencyCode: "USD",
    },
    {
        id: "je_02",
        entryNumber: "JE-1041",
        date: "2026-05-08",
        description: "Reclass: shop supplies → COGS",
        status: "POSTED",
        source: "MANUAL",
        amount: "1284.50",
        currencyCode: "USD",
    },
    {
        id: "je_03",
        entryNumber: "JE-1040",
        date: "2026-05-08",
        description: "Receipt · INV-2042 (Cedar & Co.)",
        status: "POSTED",
        source: "SYSTEM",
        amount: "5420.00",
        currencyCode: "USD",
    },
    {
        id: "je_04",
        entryNumber: "JE-1039",
        date: "2026-05-07",
        description: "Depreciation · April",
        status: "DRAFT",
        source: "MANUAL",
        amount: "3150.00",
        currencyCode: "USD",
    },
    {
        id: "je_05",
        entryNumber: "JE-1038",
        date: "2026-05-07",
        description: "FX revaluation · EUR holdings",
        status: "DRAFT",
        source: "SYSTEM",
        amount: "412.18",
        currencyCode: "USD",
    },
];

export const revenueTrend: TrendPoint[] = [
    { label: "Dec", revenue: 142000, expenses: 118400 },
    { label: "Jan", revenue: 156800, expenses: 121200 },
    { label: "Feb", revenue: 149200, expenses: 124000 },
    { label: "Mar", revenue: 168400, expenses: 130600 },
    { label: "Apr", revenue: 174200, expenses: 132800 },
    { label: "May", revenue: 188400, expenses: 138200 },
];
