import type { BillLineResponse, BillPaymentResponse, BillResponse } from "@/lib/api/finance/bills";
import { MOCK_TODAY } from "../../../_data/mock-anchor";

const ORG_ID = "org_hd_millwork";

export const apVendors = [
    { id: "vend_01", name: "Westline Hardwoods" },
    { id: "vend_02", name: "Brassworks Co." },
    { id: "vend_03", name: "Halberd Finishing Supplies" },
    { id: "vend_04", name: "Drayton Freight" },
    { id: "vend_05", name: "Pacific Power & Light" },
    { id: "vend_06", name: "Hadley Insurance Group" },
    { id: "vend_07", name: "Granite & Co. Stone" },
    { id: "vend_08", name: "Mills Custom Metalwork" },
] as const;

export const expenseAccounts = [
    { id: "acc_5000", code: "5000", name: "COGS — Lumber" },
    { id: "acc_5010", code: "5010", name: "COGS — Hardware & finishes" },
    { id: "acc_5020", code: "5020", name: "COGS — Subcontractors" },
    { id: "acc_6100", code: "6100", name: "Utilities" },
    { id: "acc_6200", code: "6200", name: "Insurance" },
    { id: "acc_6300", code: "6300", name: "Freight & shipping" },
] as const;

const today = new Date(MOCK_TODAY);
const daysFromToday = (offset: number) => {
    const d = new Date(today);
    d.setDate(d.getDate() + offset);
    return d.toISOString().slice(0, 10);
};
const isoDateTime = (offset: number) => {
    const d = new Date(today);
    d.setDate(d.getDate() + offset);
    d.setHours(11, 18, 0, 0);
    return d.toISOString();
};

const line = (accountId: string, description: string, amount: string): BillLineResponse => {
    const acc = expenseAccounts.find((a) => a.id === accountId)!;
    return {
        accountId,
        accountCode: acc.code,
        accountName: acc.name,
        amount,
        description,
    };
};

const payment = (
    id: string,
    billId: string,
    offset: number,
    amount: string,
    paymentMethod: BillPaymentResponse["paymentMethod"],
    referenceNumber: string,
): BillPaymentResponse => ({
    id,
    billId,
    paymentDate: daysFromToday(offset),
    amount,
    baseCurrencyAmount: amount,
    exchangeRate: "1.0",
    paymentMethod,
    referenceNumber,
    journalEntryId: `je_${id}`,
    createdBy: "Hadi Karimov",
    createdAt: isoDateTime(offset),
});

type BillSeed = Omit<
    BillResponse,
    | "organizationId"
    | "exchangeRate"
    | "baseCurrencyAmount"
    | "baseCurrencyTaxAmount"
    | "baseCurrencyAmountPaid"
    | "createdAt"
    | "updatedAt"
> & { _createdOffset: number };

const seeds: BillSeed[] = [
    {
        id: "bill_01",
        billNumber: "WL-44218",
        vendorId: "vend_01",
        vendorName: "Westline Hardwoods",
        date: daysFromToday(-32),
        dueDate: daysFromToday(-2),
        referenceNumber: "PO-MW-0418",
        taxGroupId: null,
        status: "PARTIALLY_PAID",
        lines: [line("acc_5000", "White oak rift cut, 240 bdft", "4860.00")],
        totalAmount: "4860.00",
        taxAmount: "0.00",
        amountPaid: "2400.00",
        currencyCode: "USD",
        journalEntryId: "je_bill_01",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-31),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -32,
    },
    {
        id: "bill_02",
        billNumber: "BW-2026-0142",
        vendorId: "vend_02",
        vendorName: "Brassworks Co.",
        date: daysFromToday(-21),
        dueDate: daysFromToday(9),
        referenceNumber: null,
        taxGroupId: null,
        status: "APPROVED",
        lines: [line("acc_5010", "Antique brass pulls, 96-pack", "1184.00")],
        totalAmount: "1184.00",
        taxAmount: "0.00",
        amountPaid: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_bill_02",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-20),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -21,
    },
    {
        id: "bill_03",
        billNumber: "HFS-90341",
        vendorId: "vend_03",
        vendorName: "Halberd Finishing Supplies",
        date: daysFromToday(-58),
        dueDate: daysFromToday(-28),
        referenceNumber: "PO-MW-0388",
        taxGroupId: null,
        status: "APPROVED",
        lines: [
            line("acc_5010", "Conversion varnish, 5gal x 6", "742.50"),
            line("acc_5010", "Stain — natural walnut, 1gal x 4", "186.00"),
        ],
        totalAmount: "928.50",
        taxAmount: "0.00",
        amountPaid: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_bill_03",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-57),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -58,
    },
    {
        id: "bill_04",
        billNumber: "DF-INV-7812",
        vendorId: "vend_04",
        vendorName: "Drayton Freight",
        date: daysFromToday(-12),
        dueDate: daysFromToday(18),
        referenceNumber: null,
        taxGroupId: null,
        status: "APPROVED",
        lines: [line("acc_6300", "LTL freight, Apr deliveries", "612.40")],
        totalAmount: "612.40",
        taxAmount: "0.00",
        amountPaid: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_bill_04",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-11),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -12,
    },
    {
        id: "bill_05",
        billNumber: "PPL-MAR2026",
        vendorId: "vend_05",
        vendorName: "Pacific Power & Light",
        date: daysFromToday(-44),
        dueDate: daysFromToday(-14),
        referenceNumber: null,
        taxGroupId: null,
        status: "PAID",
        lines: [line("acc_6100", "Shop electric — March 2026", "1820.16")],
        totalAmount: "1820.16",
        taxAmount: "0.00",
        amountPaid: "1820.16",
        currencyCode: "USD",
        journalEntryId: "je_bill_05",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-43),
        approvedBy: "Emma Voss",
        paidAt: isoDateTime(-15),
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -44,
    },
    {
        id: "bill_06",
        billNumber: "HIG-Q2-26",
        vendorId: "vend_06",
        vendorName: "Hadley Insurance Group",
        date: daysFromToday(-3),
        dueDate: daysFromToday(27),
        referenceNumber: "POL-994412",
        taxGroupId: null,
        status: "DRAFT",
        lines: [line("acc_6200", "General liability, Q2 2026 premium", "3960.00")],
        totalAmount: "3960.00",
        taxAmount: "0.00",
        amountPaid: "0.00",
        currencyCode: "USD",
        journalEntryId: null,
        createdBy: "Hadi Karimov",
        approvedAt: null,
        approvedBy: null,
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -3,
    },
    {
        id: "bill_07",
        billNumber: "GS-1142",
        vendorId: "vend_07",
        vendorName: "Granite & Co. Stone",
        date: daysFromToday(-95),
        dueDate: daysFromToday(-65),
        referenceNumber: "PO-MW-0301",
        taxGroupId: null,
        status: "APPROVED",
        lines: [line("acc_5010", "Soapstone slab, 84 sqft", "2940.00")],
        totalAmount: "2940.00",
        taxAmount: "0.00",
        amountPaid: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_bill_07",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-94),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -95,
    },
    {
        id: "bill_08",
        billNumber: "MCM-822",
        vendorId: "vend_08",
        vendorName: "Mills Custom Metalwork",
        date: daysFromToday(-6),
        dueDate: daysFromToday(24),
        referenceNumber: null,
        taxGroupId: null,
        status: "DRAFT",
        lines: [line("acc_5020", "Blackened steel hood, fab + delivery", "5240.00")],
        totalAmount: "5240.00",
        taxAmount: "0.00",
        amountPaid: "0.00",
        currencyCode: "USD",
        journalEntryId: null,
        createdBy: "Hadi Karimov",
        approvedAt: null,
        approvedBy: null,
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -6,
    },
    {
        id: "bill_09",
        billNumber: "WL-44310",
        vendorId: "vend_01",
        vendorName: "Westline Hardwoods",
        date: daysFromToday(-9),
        dueDate: daysFromToday(21),
        referenceNumber: "PO-MW-0429",
        taxGroupId: null,
        status: "APPROVED",
        lines: [line("acc_5000", "Cherry, plain sawn, 180 bdft", "2160.00")],
        totalAmount: "2160.00",
        taxAmount: "0.00",
        amountPaid: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_bill_09",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-8),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -9,
    },
    {
        id: "bill_10",
        billNumber: "DF-INV-7790",
        vendorId: "vend_04",
        vendorName: "Drayton Freight",
        date: daysFromToday(-72),
        dueDate: daysFromToday(-42),
        referenceNumber: null,
        taxGroupId: null,
        status: "PAID",
        lines: [line("acc_6300", "LTL freight, Feb deliveries", "488.20")],
        totalAmount: "488.20",
        taxAmount: "0.00",
        amountPaid: "488.20",
        currencyCode: "USD",
        journalEntryId: "je_bill_10",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-71),
        approvedBy: "Emma Voss",
        paidAt: isoDateTime(-43),
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -72,
    },
    {
        id: "bill_11",
        billNumber: "BW-2026-0089",
        vendorId: "vend_02",
        vendorName: "Brassworks Co.",
        date: daysFromToday(-50),
        dueDate: daysFromToday(-20),
        referenceNumber: null,
        taxGroupId: null,
        status: "VOID",
        lines: [line("acc_5010", "Inset cup pulls — wrong finish, returned", "412.00")],
        totalAmount: "412.00",
        taxAmount: "0.00",
        amountPaid: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_bill_11",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-49),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: isoDateTime(-44),
        voidedBy: "Emma Voss",
        voidReason: "Wrong finish on shipment, returned to vendor",
        _createdOffset: -50,
    },
    {
        id: "bill_12",
        billNumber: "PPL-APR2026",
        vendorId: "vend_05",
        vendorName: "Pacific Power & Light",
        date: daysFromToday(-14),
        dueDate: daysFromToday(16),
        referenceNumber: null,
        taxGroupId: null,
        status: "APPROVED",
        lines: [line("acc_6100", "Shop electric — April 2026", "1948.92")],
        totalAmount: "1948.92",
        taxAmount: "0.00",
        amountPaid: "0.00",
        currencyCode: "USD",
        journalEntryId: "je_bill_12",
        createdBy: "Hadi Karimov",
        approvedAt: isoDateTime(-13),
        approvedBy: "Emma Voss",
        paidAt: null,
        voidedAt: null,
        voidedBy: null,
        voidReason: null,
        _createdOffset: -14,
    },
];

function expand(seed: BillSeed): BillResponse {
    const { _createdOffset, ...rest } = seed;
    return {
        ...rest,
        organizationId: ORG_ID,
        exchangeRate: "1.0",
        baseCurrencyAmount: rest.totalAmount,
        baseCurrencyTaxAmount: rest.taxAmount,
        baseCurrencyAmountPaid: rest.amountPaid,
        createdAt: isoDateTime(_createdOffset),
        updatedAt: isoDateTime(_createdOffset + 1),
    };
}

export const bills: BillResponse[] = seeds.map(expand);

export const billPayments: BillPaymentResponse[] = [
    payment("bp_01", "bill_01", -10, "2400.00", "BANK_TRANSFER", "ACH-22019"),
    payment("bp_05a", "bill_05", -16, "1820.16", "BANK_TRANSFER", "ACH-21822"),
    payment("bp_10a", "bill_10", -44, "488.20", "CHECK", "CHK-4811"),
];
